// Generated by CoffeeScript 1.3.1
(function() {
  var Spine;

<<<<<<< HEAD
  Spine = (function() {
    var _ref;
    return (_ref = this.Spine) != null ? _ref : require('spine');
  })();
=======
  Spine = this.Spine || require('spine');
>>>>>>> triggers

  Spine.Model.Local = {
    extended: function() {
      this.change(this.saveLocal);
      return this.fetch(this.loadLocal);
    },
    saveLocal: function() {
      var result;
      result = JSON.stringify(this);
      return localStorage[this.className] = result;
    },
    loadLocal: function() {
      var result;
      result = localStorage[this.className];
      return this.refresh(result || [], {
        clear: true
      });
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Spine.Model.Local;
  }

}).call(this);
